/**
 * Every user-facing string in the app, in one editable place.
 *
 * Edit the text here and it changes everywhere it is shown — components read
 * from this file and never hold copy of their own. Strings that need a value
 * dropped into them are written as small functions, so the whole sentence
 * stays here rather than being assembled in a component.
 *
 * Organised by surface, in roughly the order a player meets them.
 */

export const copy = {
  // ── App chrome ──────────────────────────────────────────────────────────
  nav: {
    dashboard: "Dashboard",
    stats: "Stats",
    history: "History",
    settings: "Settings",
    liveGame: "Live game",
    liveGameShort: "Live",
    trackGame: "Track a game",
    trackGameShort: "Track",
  },

  footer: {
    feedback: "Feedback",
    changelog: "What's new",
    roadmap: "Roadmap",
    help: "Help",
    admin: "Admin",
    signOut: "Sign out",
    madeBy: "Made by Aayush",
  },

  gameFlow: {
    logTitle: "Log Game",
    editTitle: "Edit Game",
    deleteGameLabel: "Delete game",
    restorePanelLabel: "Restore panel",
    minimizePanelLabel: "Minimize panel",
    closePanelLabel: "Close panel",
    confirmDeleteTitle: "Delete this game?",
    confirmDeleteBody: "This can't be undone",
    confirmDeleteCancel: "Cancel",
    confirmDeleteConfirm: "Delete",
    discardTitle: "Discard in-progress game log?",
    discardBody: "You have unsaved changes that will be lost",
    discardKeepEditing: "Keep Editing",
    discardConfirm: "Discard",
  },

  toasts: {
    gameLogged: "Game logged!",
    gameUpdated: "Game updated!",
    gameSaved: "Game saved!",
    gameSaveFailed: "Couldn't save game",
    gameNotFound: "Could not find that game to edit.",
    loadFailed: "Failed to load games from the server.",
    saveFailed: "Failed to save game.",
    updateFailed: "Failed to update game.",
    deleteFailed: "Failed to delete game.",
    importFailed: "Failed to import games to the server.",
    clearFailed: "Failed to clear games from the server.",
    loadingGames: "Loading games…",
  },

  // ── Onboarding walkthrough ──────────────────────────────────────────────
  tour: {
    stepCounter: (current: number, total: number) => `Step ${current} of ${total}`,
    skip: "Skip tour",
    back: "Back",
    next: "Next",
    finish: "Finish",
    sampleBadge: "Sample data",
    sampleExplainer:
      "(These are example games)",
    dialogLabel: "App walkthrough",
    sketch: {
      opponentName: "Player 2",
      youName: "You",
      attack: "Attack",
      tally: "−5",
      opponentLife: 33,
      yourLife: 35,
    },
    steps: {
      welcome: {
        title: "Welcome to Elder Dragon Actuary",
        body: "Welcome! Here's a quick tour of the three screens you'll use most: your stats, tracking a finished game, and running a game at the table.",
      },
      stats_overview: {
        title: "Your game performance",
        body: "Win rate, average winning turn, and other top line performance stats",
      },
      stats_range: {
        title: "Measure over time",
        body: "Choose your stats across different time periods here",
      },
      stats_commanders: {
        title: "Deck by deck",
        body: "Every commander you've sleeved up, sortable by win rate, winning turn, or total wins",
      },
      stats_elo: {
        title: "ELO ratings",
        body: "Your pods and commanders each carry a rating that moves after every game, so beating a stacked table counts for more than beating a jank one",
      },
      track_entry: {
        title: "Track a finished game",
        body: "Tap here to log a game you've already played",
      },
      track_pod: {
        title: "Start with the table",
        body: "Pick players, or reuse an old pod",
      },
      track_players: {
        title: "Seats, commanders, winner",
        body: "Give each player a commander and a seat, then mark the winner",
      },
      track_save: {
        title: "Save it",
        body: "Saving drops the game straight into your history. This computes stats and ELO",
      },
      live_entry: {
        title: "Playing right now?",
        body: "Live game turns your device into the table's life tracker, and logs the game when it ends.",
      },
      live_setup: {
        title: "Pick the table",
        body: "Tap a recent pod to jump straight in, or build from scratch. Commanders can be set on the board",
      },
      live_board: {
        title: "On the board",
        body: "Move players to the right seat before you start!",
        bullets: [
          "Tap − or + to change life — a running total shows what you've tapped so far.",
          "Hold either button for ±10.",
          "Drag Attack from your seat onto another to deal damage, with commander, poison, and lifelink toggles.",
          "Drop on the centre target to hit every opponent at once.",
        ],
      },
      done: {
        title: "That's the tour",
        body: "Save the live game when one player is left and it lands in your history with the winning turn already filled in.",
      },
    },
  },
  // ── Settings ────────────────────────────────────────────────────────────
  settings: {
    heading: "Settings",
    profile: {
      cardTitle: "Profile",
      displayNamePlaceholder: "Display name",
      save: "Save",
      saved: "Display name saved",
      shareInvite: "Share invite",
      signOut: "Sign out",
      inviteTitle: "Invite someone!",
      inviteQrAlt: "Invite QR code",
      inviteQrUnavailable: "QR unavailable",
    },
    gettingStarted: {
      cardTitle: "Getting started",
      replayLabel: "Replay the walkthrough",
      replaySub: "A guided tour of stats, tracking a game, and the live board.",
      replayButton: "Start tour",
    },
    feedback: {
      cardTitle: "Feedback & support",
      sendFeedback: "Send feedback",
      changelog: "What's new",
      roadmap: "Roadmap",
      helpCenter: "Help center",
    },
    appearance: {
      cardTitle: "Appearance",
      modeLabel: "Mode",
      modeSub: "System follows your device appearance.",
      modes: { system: "System", light: "Light", dark: "Dark" },
      accentLabel: "Accent",
      accentSub: "Used for actions, wins, and highlights.",
    },
    data: {
      cardTitle: "Data",
      exportLabel: "Export games",
      exportSub: (count: number) => `Download all ${count} games as JSON or CSV.`,
      exportJson: "JSON",
      exportCsv: "CSV",
      restoreLabel: "Restore from backup",
      restoreSub: "Import a previously exported JSON. Replaces all cloud data.",
      restoreTestJson: "Test JSON",
      restoreButton: "Restore",
      deleteLabel: "Delete all data",
      deleteSub: "Permanently removes every logged game.",
      deleteButton: "Delete…",
      deleteConfirm: "Confirm",
      deleteCancel: "Cancel",
      deleted: "All data deleted.",
      imported: (count: number) => `Imported ${count} game${count !== 1 ? "s" : ""}.`,
      importFailed: (reason?: string) => `Import failed: ${reason}`,
      testJsonLoaded: (count: number) => `Loaded test JSON with ${count} game${count !== 1 ? "s" : ""}.`,
      testJsonFailed: (reason?: string) => `Load test JSON failed: ${reason}`,
      testJsonUnavailable: "Could not load test JSON.",
      testJsonInvalid: "Load test JSON file was not found or is not valid JSON.",
    },
  },
  // ── Stats page ──────────────────────────────────────────────────────────
  stats: {
    heading: "Stats",
    sampleBadge: "Sample data",
    ranges: { allTime: "All time", thisYear: "This year", last90: "Last 90 days" },
    empty: {
      title: "No games logged yet",
      body: "Log a game to see your stats here.",
      cta: "Track a game",
    },
    winRate: "Win rate",
    avgWinTurn: "Avg win turn",
    avgWinTurnSub: "when you win",
    withFastMana: "With fast mana",
    vsFastMana: "Vs fast mana",
    rateSub: (wins: number, games: number) => `${wins} wins / ${games} games`,
    lossSub: (losses: number, games: number) => `${losses} losses / ${games} games`,
    noGames: "no games",
    streak: (count: number, type: "win" | "loss") => `${count} ${type} streak`,
    win: "W",
    loss: "L",
    topWaysToWin: "Top ways to win",
    winRateByStartingTurn: "Win rate by starting turn",
    seatToPlay: (ordinal: string) => `${ordinal} to play`,
    winRateByMonth: "Win rate by month",
    baseline: "— — 25% baseline",
    monthTooltip: (month: string, wins: number, games: number) => `${month}: ${wins} wins / ${games} games`,
    byPodSize: "By pod size",
    podSize: (size: number) => `${size} players`,
    noData: "No data yet.",
    commanderColors: "Commander colors",
    mostPlayed: "Most played",
    mostSuccessful: "Most successful",
    archnemesisColors: "Archnemesis colors",
    gamesCount: (games: number) => `${games} game${games !== 1 ? "s" : ""}`,
    commanderPerformance: "Commander performance",
    sortBy: "Sort by",
    sortOptions: { winRate: "Win rate", winTurn: "Winning turn", totalWins: "Total wins" },
    sortAsc: "Asc",
    sortDesc: "Desc",
    eloRatings: "ELO ratings",
  },
  // ── Dashboard ───────────────────────────────────────────────────────────
  dashboard: {
    searchPlaceholder: "Search a commander to log a game…",
    empty: {
      title: "No games logged yet",
      body: "Track a game to see your stats here.",
      cta: "Track a game",
    },
    games: "Games",
    gamesSub: "all-time",
    winRate: "Win rate",
    winRateSub: (wins: number, games: number) => `${wins} of ${games} games`,
    bestSeat: "Best seat",
    bestSeatSub: (rate: number, ordinal: string) => `${rate}% ${ordinal} to play`,
    noSeatData: "no seat data",
    topCommander: "Top commander",
    topCommanderSub: (rate: number, games: number) => `${rate}% over ${games} games`,
    favoriteCommanders: "Favorite commanders",
    trackGame: "Track game",
    recentGames: "Recent games",
    gameHistory: "Game history",
    noGamesYet: "No games yet.",
  },

  // ── History ─────────────────────────────────────────────────────────────
  history: {
    filters: { all: "All", wins: "Wins", losses: "Losses" },
    groupBy: { date: "By date", pod: "By pod" },
    allHeroes: "All heroes",
    versus: (opponents: string) => `vs ${opponents}`,
    soloLog: "Solo log",
    editGame: "Edit game",
    deleteGame: "Delete game",
    confirmDelete: "Delete this game?",
    noMatch: "No games match",
    noMatchBody: "Try a different filter.",
  },
  // ── Log / edit a game ───────────────────────────────────────────────────
  logGame: {
    playerCountHeading: "How many players?",
    podLabel: "Or, select an existing pod",
    podPlaceholder: "Select a pod…",
    addBracket: "Add game bracket (Optional)",
    bracketHeading: "Select game bracket",
    bracketLink: "About game brackets",
    playersHeading: "Players",
    keyWinconCards: "Key wincon cards (Optional)",
    winconSearchPlaceholder: "Search for key wincon cards…",
    winConditionsHeading: "How did they win (Optional)",
    notesLabel: "Notes (optional)",
    notesPlaceholder: "Any additional notes…",
    cancel: "Cancel",
    save: "Save Game",
    saveEdit: "Save Changes",
    errorKoTiming: "Winning turn can't be after all opponents are knocked out",
    errorGeneric: "Please fill in all highlighted fields.",
    removeCard: (cardName: string) => `Remove ${cardName}`,
    seatLabel: (seat: number) => `Seat ${seat}`,
    /** the win-condition chips, shared by the log form and the live game */
    winConditions: [
      "Commander Damage",
      "Lethal Combat Damage",
      "Combat Trick",
      "Lethal Non-Combat Damage",
      "Players Decked Out",
      "Alternate Wincon",
      "Infinite Loop",
      "Infinite Life-Gain",
      "Infinite Mana",
      "Asymmetric Board Wipe",
      "Poison or Infect",
    ],
  },
  // ── Live game ───────────────────────────────────────────────────────────
  live: {
    setup: {
      startTitle: "Start a live game",
      startSubtitle: "Tap a pod to jump in — set commanders at the table.",
      yourPods: "Your pods · tap to start",
      editRoster: "Edit roster",
      newTable: "New table",
      rosterTitlePod: "Tonight's table",
      rosterTitleNew: "Who's playing?",
      rosterSubtitle: "Add, remove, or rename players. Commanders are set at the table.",
      playersCount: (count: number) => `Players · ${count}`,
      playersMax: " (max)",
      dragToReorder: "Drag to reorder",
      removePlayer: "Remove player",
      addPlayerPlaceholder: "Add player — type a name, press Enter",
      tableLayout: "Table layout",
      startGame: "Start game",
      back: "Back",
    },
    board: {
      preGameHint: "Drag seats · set commanders · then roll",
      readyToRoll: "Ready to roll",
      whoGoesFirst: "Who goes first?",
      checkTheirSeat: "Check their seat",
      rolling: "Rolling…",
      highRoll: "High roll (D20)",
      confirm: "Confirm",
      startsHere: "Starts here",
      start: "Start",
      endTurn: "End turn",
      endGame: "End game",
      endGameConfirmTitle: "End game early?",
      endGameConfirmBody: "This will end the game even though there are still players alive.",
      cancel: "Cancel",
      undo: "undo",
      endGameEarly: "end game early",
      dragToSwap: "Drag to swap",
      dragToSwapLabel: "Drag to swap seat",
      attack: "Attack",
      target: "Target",
      damageAll: "Damage",
      damageAllSecondLine: "all",
      allPlayers: "All players",
      setCommander: "Set commander",
      commander: "Commander",
      knockout: "KO",
      revive: "Revive",
      loseLifeLabel: "lose life (hold for 10)",
      gainLifeLabel: "gain life (hold for 10)",
      viewDamageLabel: "View commander and poison damage",
      winnerBanner: (name: string) => `${name} wins!`,
      gameOver: "Game over",
      saveGame: "Save game",
      rematch: "Rematch",
      discardGame: "Discard game",
    },
    damageEntry: {
      minusLabel: "minus (hold for 10)",
      plusLabel: "plus (hold for 10)",
      commanderMod: "⚔ Cmdr",
      poisonMod: "☠ Poison",
      lifelinkMod: "❤ Lifelink",
      pickAmount: "Pick an amount",
      deal: (amount: number) => `Deal ${amount}`,
      poison: (amount: number) => `Poison ${amount}`,
    },
    damageModal: {
      subtitle: "Damage taken",
      empty: "No commander or poison damage yet",
      commanderDamage: "Commander damage",
      poison: "Poison",
      poisonCounters: "☠ Poison counters",
    },
    commanderGate: {
      title: "Set commanders to save",
      body: "Every player needs a commander so the game counts toward stats.",
      missingHint: "No commander — tap to set",
      cancel: "Cancel",
      missingCount: (count: number) => `${count} missing`,
      save: "Save game",
    },
    wincon: {
      title: (winner: string) => `How did ${winner} win?`,
      fallbackWinner: "the winner",
      subtitle: "Optional — helps track win patterns",
      winConditions: "Win conditions",
      keyWinconCards: "Key wincon cards",
      searchPlaceholder: "Search for key wincon cards…",
      fastMana: "Fast mana",
      bracket: "Game bracket (optional)",
      notes: "Notes (optional)",
      notesPlaceholder: "Any notes about this game…",
      skip: "Skip",
      save: "Save & continue",
    },
  },
  // ── Signed-out home page ────────────────────────────────────────────────
  marketing: {
    signIn: "Sign in",
    cta: "Track your first game",
    eyebrow: "The actuary for your playgroup",
    headline: "Shuffle, Ramp, Study, Send.",
    subhead:
      "Log Commander games in two taps and unlock in-depth statistics — win rates by seat and commander, performance across your pods, the cards that actually close games, and a lot more. Free, and it works at any table.",
    demoCta: "Explore the demo",
    closingHeadline: "Politics is temporary. Variance is forever.",
    closingBody: "Start your ledger now — the numbers will be more embarrassing than you think.",
    madeBy: "Made by Aayush.",
    signOff: "Be kind, scoop at sorcery speed.",
  },

  // ── Sign in / sign up ───────────────────────────────────────────────────
  auth: {
    signInTitle: "Sign in to your account",
    signUpTitle: "Create a new account",
    emailPlaceholder: "you@example.com",
    passwordPlaceholder: "••••••••",
    invitePlaceholder: "Invite code",
    signInButton: "Sign In",
    signUpButton: "Create Account",
    switchToSignUp: "Sign up",
    switchToSignIn: "Sign in",
    confirmEmail: "Check your email for a confirmation link, then sign in.",
    errors: {
      missingCredentials: "Email and password are required.",
      passwordMismatch: "Passwords do not match.",
      missingInvite: "Invite code is required.",
      passwordTooShort: "Password must be at least 6 characters.",
    },
  },

  // ── Admin dashboard ─────────────────────────────────────────────────────
  admin: {
    columns: {
      account: "Account",
      games: "Games",
      lastGame: "Last game",
      activeDays: "Active days",
      winRate: "Win rate",
      joined: "Joined",
    },
    notAdmin: "This page is only available to administrators.",
    refresh: "Refresh",
    accounts: "Accounts",
    activated: "Activated",
    active30d: "Active (30d)",
    filterPlaceholder: "Filter by email…",
    sortAccountsBy: "Sort accounts by",
    sortAscending: "Sort ascending",
    sortDescending: "Sort descending",
    noMatch: "No accounts match that filter.",
    noAccounts: "No accounts yet.",
  },
  // ── Shared components ───────────────────────────────────────────────────
  player: {
    commander: "Commander",
    partner: "Partner",
    addPartner: "Add partner",
    removePartner: "Remove",
    pickCommander: "Pick a commander",
    pickPartner: "Pick a partner",
    seat: "Seat (turn order)",
    fastMana: "Fast Mana",
    addFastMana: "Add fast mana",
    fastManaPlaceholder: "Sol Ring, Mana Crypt… (optional)",
    winner: "Winner",
    turnPlaceholder: "turn",
    you: "You",
    otherPlayer: "Player",
    seatOrdinals: ["First", "Second", "Third", "Fourth", "Fifth", "Sixth"],
    unknownCommander: "Unknown commander",
    unknownCommanderTitle: "Unknown Commander",
  },

  pickers: {
    commanderTitle: "Pick a commander",
    commanderSearchTitle: "Search commanders",
    commanderSearchPlaceholder: "Search a commander…",
    yourCommanders: "Your commanders",
    theirCommanders: (name: string) => `${name}'s commanders`,
    playedRelative: (relative: string) => `Played ${relative}`,
    playedOnce: "Played once",
    loggedRelative: (relative: string) => `Logged ${relative}`,
    loggedOnce: "Logged once",
    clearSearch: "Clear search",
    cardSearchPlaceholder: "Search any card…",
    fastManaSearchTitle: "Search fast mana",
    fastManaTitle: "Add fast mana",
    fastManaSearchPlaceholder: "Search a card…",
    commanderInline: {
      placeholder: "Search commander…",
      loading: "Loading…",
      typePlaceholder: "Type a commander name…",
      recentHeading: "Recent",
      noResults: "No commanders found.",
    },
    playerNames: {
      empty: "No saved players yet.",
      noMatch: "No saved players match.",
      addPlaceholder: "Add a new name…",
    },
  },

  gameDetail: {
    opponents: "Opponents",
    win: "Win",
    loss: "Loss",
    won: "Won",
    lost: "Lost",
    notes: "Notes",
    winConditions: "Win Conditions",
    editGame: "Edit Game",
    deleteGame: "Delete Game",
    editGameLabel: "Edit game",
  },

  elo: {
    commanderTab: "Commander ELO",
    podTab: "Pod ELO",
    startPoint: "Start",
    overall: "Overall ELO",
    perCommander: "Per-Commander ELO",
    pod: "Pod ELO",
  },

  commanderStats: {
    winRate: "Win Rate",
    avgWinTurn: "Avg Win Turn",
    withFastMana: "With Fast Mana",
  },

  bracketPie: {
    wins: "Wins",
  },
  // ── History milestones (the badges on the timeline) ──────────────────────
  milestones: {
    veteranTiers: {
      ten: "Getting comfortable",
      twenty: "Seasoned pilot",
      fifty: "Grizzled veteran",
      hundred: "True master",
    },
    firstGame: "First game logged",
    milestoneGame: (ordinal: string) => `${ordinal} game played`,
    debut: (commander: string) => `${commander} debut`,
    debutDetail: "First time piloting this deck",
    veteranGame: (ordinal: string, commander: string) => `${ordinal} game with ${commander}`,
    newRival: "New rival",
    firstWin: "First win",
    careerWin: (ordinal: string) => `${ordinal} career win`,
    winStreak: (streak: number) => `${streak}-win streak`,
    comeback: "Comeback win",
    comebackDetail: (slump: number) => `Snapped a ${slump}-loss slump`,
    nemesis: "Nemesis slain",
    nemesisDetail: (commander: string, times: number) => `${commander} had beaten you ${times}×`,
    colorPioneer: (colors: string) => `First win in ${colors}`,
    colorPioneerDetail: "New colors on the board",
    toughSeat: (seat: number) => `Won from seat ${seat}`,
    toughSeatDetail: "Back-of-the-table win",
    underdog: "Beat a fast-mana start",
    underdogDetail: "No fast mana of your own",
    fastWin: (turn: number) => `Turn-${turn} kill`,
    slowBurn: (turn: number) => `Turn-${turn} grind`,
    bracketBuster: "Bracket buster",
    bracketBusterDetail: (bracket: number) => `Won up at bracket ${bracket}`,
    wincon: (card: string) => `Closed with ${card}`,
    lossStreak: (streak: number) => `${streak}-loss streak`,
    knockout: (turn: number) => `Knocked out turn ${turn}`,
    flawlessMonth: "Flawless month",
    flawlessMonthDetail: (wins: number, month: string) => `${wins}–0 in ${month}`,
    colorNames: { W: "White", U: "Blue", B: "Black", R: "Red", G: "Green" },
    colorless: "Colorless",
    fiveColor: "5-Color",
    mono: (color: string) => `Mono-${color}`,
  },

  // ── Exported CSV column headers ─────────────────────────────────────────
  csv: {
    date: "Date",
    bracket: "Bracket",
    playerCommander: (n: number) => `Player ${n} Commander`,
    playerFastMana: (n: number) => `Player ${n} Fast Mana`,
    playerKoTurn: (n: number) => `Player ${n} KO Turn`,
    winner: "Winner",
    winTurn: "Win Turn",
    notes: "Notes",
    winConditions: "Win Conditions",
    keyWinconCards: "Key Wincon Cards",
  },
} as const
